repos:
  # Versioning: Commit Messages & Changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.1
    hooks:
      - id: prettier
        args:
          [
            '--single-quote',
            '--trailing-comma=all',
            '--ignore-unknown',
            '--no-error-on-unmatched-pattern',
            '--ignore-path',
            './.cz.yaml',
          ]

  # Lint: Javascript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.17.0
    hooks:
      - id: eslint
        args: ['--ext', '.js,.ts,.vue']

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        args: ['--fix', '--disable', 'MD024']
